/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CurrencyConverterProject;

import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;


public class ShowCurrency extends javax.swing.JFrame {

    /**
     * Creates new form ShowCurrency
     */
    public ShowCurrency() {
        initComponents();
        populateCurrencies("USD");                                                  // Removes the horizontal scrollbar. Code from:
        ValuesScrollPane.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);  // https://stackoverflow.com/questions/1727840/disable-horizontal-scroll-in-jscrollpane
    }
    // This method will fill the live value of cryptocurrencies using data from the api
    private void populateCurrencies(String base) {
        LivePrices data = new LivePrices();
        String liveUSDPrice = data.getExchangeRate(base, "USD"); // API calls
        String liveEURPrice = data.getExchangeRate(base, "EUR");
        String liveJPYPrice = data.getExchangeRate(base, "JPY");
        String liveGBPPrice = data.getExchangeRate(base, "GBP");
        String liveAUDPrice = data.getExchangeRate(base, "AUD");
        String liveCADPrice = data.getExchangeRate(base, "CAD");
        String liveCHFPrice = data.getExchangeRate(base, "CHF");
        String liveCNYPrice = data.getExchangeRate(base, "CNY");
        String liveSEKPrice = data.getExchangeRate(base, "SEK");
        String liveMXNPrice = data.getExchangeRate(base, "MXN");
        USDPrice.setText(liveUSDPrice); // Set text after API call
        EURPrice.setText(liveEURPrice);
        JPYPrice.setText(liveJPYPrice);
        GBPPrice.setText(liveGBPPrice);
        AUDPrice.setText(liveAUDPrice);
        CADPrice.setText(liveCADPrice);
        CHFPrice.setText(liveCHFPrice);
        CNYPrice.setText(liveCNYPrice);
        SEKPrice.setText(liveSEKPrice);
        MXNPrice.setText(liveMXNPrice);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        ValuesScrollPane = new javax.swing.JScrollPane();
        CurrencyContainer = new javax.swing.JPanel();
        ListPanel = new javax.swing.JPanel();
        USDPrice = new javax.swing.JLabel();
        USDLabel = new javax.swing.JLabel();
        ListPanel1 = new javax.swing.JPanel();
        EURPrice = new javax.swing.JLabel();
        EURLabel = new javax.swing.JLabel();
        ListPanel2 = new javax.swing.JPanel();
        JPYPrice = new javax.swing.JLabel();
        JPYLabel = new javax.swing.JLabel();
        ListPanel3 = new javax.swing.JPanel();
        GBPPrice = new javax.swing.JLabel();
        GBPLabel = new javax.swing.JLabel();
        ListPanel4 = new javax.swing.JPanel();
        AUDPrice = new javax.swing.JLabel();
        AUDLabel = new javax.swing.JLabel();
        ListPanel5 = new javax.swing.JPanel();
        CADPrice = new javax.swing.JLabel();
        CADLabel = new javax.swing.JLabel();
        ListPanel6 = new javax.swing.JPanel();
        CHFPrice = new javax.swing.JLabel();
        CHFLabel = new javax.swing.JLabel();
        ListPanel7 = new javax.swing.JPanel();
        CNYPrice = new javax.swing.JLabel();
        CNYLabel = new javax.swing.JLabel();
        ListPanel8 = new javax.swing.JPanel();
        SEKPrice = new javax.swing.JLabel();
        SEKLabel = new javax.swing.JLabel();
        ListPanel9 = new javax.swing.JPanel();
        MXNPrice = new javax.swing.JLabel();
        MXNLabel = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        CurrencyDropdown = new javax.swing.JComboBox<>();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Live Currency Rates");

        ListPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        USDPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        USDPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USDPrice.setText("Loading...");

        USDLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        USDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USDLabel.setText("USD- US Dollar");

        javax.swing.GroupLayout ListPanelLayout = new javax.swing.GroupLayout(ListPanel);
        ListPanel.setLayout(ListPanelLayout);
        ListPanelLayout.setHorizontalGroup(
            ListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(USDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(USDPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanelLayout.setVerticalGroup(
            ListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USDPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(USDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ListPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        EURPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EURPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EURPrice.setText("Loading...");

        EURLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EURLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EURLabel.setText("EUR - European Euro");

        javax.swing.GroupLayout ListPanel1Layout = new javax.swing.GroupLayout(ListPanel1);
        ListPanel1.setLayout(ListPanel1Layout);
        ListPanel1Layout.setHorizontalGroup(
            ListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EURLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(EURPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanel1Layout.setVerticalGroup(
            ListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EURPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EURLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ListPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        JPYPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JPYPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPYPrice.setText("Loading...");

        JPYLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JPYLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPYLabel.setText("JPY - Japanese Yen");

        javax.swing.GroupLayout ListPanel2Layout = new javax.swing.GroupLayout(ListPanel2);
        ListPanel2.setLayout(ListPanel2Layout);
        ListPanel2Layout.setHorizontalGroup(
            ListPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(JPYPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanel2Layout.setVerticalGroup(
            ListPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPYPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ListPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        GBPPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GBPPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GBPPrice.setText("Loading...");

        GBPLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GBPLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GBPLabel.setText("GBP - Pound Sterling");

        javax.swing.GroupLayout ListPanel3Layout = new javax.swing.GroupLayout(ListPanel3);
        ListPanel3.setLayout(ListPanel3Layout);
        ListPanel3Layout.setHorizontalGroup(
            ListPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GBPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(GBPPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanel3Layout.setVerticalGroup(
            ListPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GBPPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GBPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ListPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AUDPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AUDPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AUDPrice.setText("Loading...");

        AUDLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AUDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AUDLabel.setText("AUD - Austrailian Dollar");

        javax.swing.GroupLayout ListPanel4Layout = new javax.swing.GroupLayout(ListPanel4);
        ListPanel4.setLayout(ListPanel4Layout);
        ListPanel4Layout.setHorizontalGroup(
            ListPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AUDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(AUDPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanel4Layout.setVerticalGroup(
            ListPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AUDPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AUDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ListPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        CADPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CADPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CADPrice.setText("Loading...");

        CADLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CADLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CADLabel.setText("CAD - Canadian Dollar");

        javax.swing.GroupLayout ListPanel5Layout = new javax.swing.GroupLayout(ListPanel5);
        ListPanel5.setLayout(ListPanel5Layout);
        ListPanel5Layout.setHorizontalGroup(
            ListPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CADLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(CADPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanel5Layout.setVerticalGroup(
            ListPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CADPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CADLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ListPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        CHFPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CHFPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CHFPrice.setText("Loading...");

        CHFLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CHFLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CHFLabel.setText("CHF - Swiss Franc");

        javax.swing.GroupLayout ListPanel6Layout = new javax.swing.GroupLayout(ListPanel6);
        ListPanel6.setLayout(ListPanel6Layout);
        ListPanel6Layout.setHorizontalGroup(
            ListPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CHFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(CHFPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanel6Layout.setVerticalGroup(
            ListPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CHFPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CHFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ListPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        CNYPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CNYPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CNYPrice.setText("Loading...");

        CNYLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CNYLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CNYLabel.setText("CNY - Chinese Yuan");

        javax.swing.GroupLayout ListPanel7Layout = new javax.swing.GroupLayout(ListPanel7);
        ListPanel7.setLayout(ListPanel7Layout);
        ListPanel7Layout.setHorizontalGroup(
            ListPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CNYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(CNYPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanel7Layout.setVerticalGroup(
            ListPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNYPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CNYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ListPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        SEKPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SEKPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SEKPrice.setText("Loading...");

        SEKLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SEKLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SEKLabel.setText("SEK - Swedish Krona");

        javax.swing.GroupLayout ListPanel8Layout = new javax.swing.GroupLayout(ListPanel8);
        ListPanel8.setLayout(ListPanel8Layout);
        ListPanel8Layout.setHorizontalGroup(
            ListPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SEKLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(SEKPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanel8Layout.setVerticalGroup(
            ListPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEKPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEKLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ListPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        MXNPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MXNPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MXNPrice.setText("Loading...");

        MXNLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MXNLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MXNLabel.setText("MXN - Mexican Peso");

        javax.swing.GroupLayout ListPanel9Layout = new javax.swing.GroupLayout(ListPanel9);
        ListPanel9.setLayout(ListPanel9Layout);
        ListPanel9Layout.setHorizontalGroup(
            ListPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MXNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(MXNPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ListPanel9Layout.setVerticalGroup(
            ListPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MXNPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MXNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout CurrencyContainerLayout = new javax.swing.GroupLayout(CurrencyContainer);
        CurrencyContainer.setLayout(CurrencyContainerLayout);
        CurrencyContainerLayout.setHorizontalGroup(
            CurrencyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrencyContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CurrencyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        CurrencyContainerLayout.setVerticalGroup(
            CurrencyContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CurrencyContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        ValuesScrollPane.setViewportView(CurrencyContainer);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        CurrencyDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "JPY", "GBP", "AUD", "CAD", "CHF", "CNY", "SEK", "MXN" }));
        CurrencyDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrencyDropdownActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(ValuesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CurrencyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrencyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ValuesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Button handling for updating the values.
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        populateCurrencies(CurrencyDropdown.getSelectedItem().toString());
    }//GEN-LAST:event_UpdateButtonActionPerformed
// Update the values if the user changes the base rate
    private void CurrencyDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrencyDropdownActionPerformed
        populateCurrencies(CurrencyDropdown.getSelectedItem().toString());
    }//GEN-LAST:event_CurrencyDropdownActionPerformed
// Add back button handling to return to the main page
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        StartWindow startWin = new StartWindow();
        startWin.show();
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowCurrency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowCurrency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AUDLabel;
    private javax.swing.JLabel AUDPrice;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CADLabel;
    private javax.swing.JLabel CADPrice;
    private javax.swing.JLabel CHFLabel;
    private javax.swing.JLabel CHFPrice;
    private javax.swing.JLabel CNYLabel;
    private javax.swing.JLabel CNYPrice;
    private javax.swing.JPanel CurrencyContainer;
    private javax.swing.JComboBox<String> CurrencyDropdown;
    private javax.swing.JLabel EURLabel;
    private javax.swing.JLabel EURPrice;
    private javax.swing.JLabel GBPLabel;
    private javax.swing.JLabel GBPPrice;
    private javax.swing.JLabel JPYLabel;
    private javax.swing.JLabel JPYPrice;
    private javax.swing.JPanel ListPanel;
    private javax.swing.JPanel ListPanel1;
    private javax.swing.JPanel ListPanel2;
    private javax.swing.JPanel ListPanel3;
    private javax.swing.JPanel ListPanel4;
    private javax.swing.JPanel ListPanel5;
    private javax.swing.JPanel ListPanel6;
    private javax.swing.JPanel ListPanel7;
    private javax.swing.JPanel ListPanel8;
    private javax.swing.JPanel ListPanel9;
    private javax.swing.JLabel MXNLabel;
    private javax.swing.JLabel MXNPrice;
    private javax.swing.JLabel SEKLabel;
    private javax.swing.JLabel SEKPrice;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel USDLabel;
    private javax.swing.JLabel USDPrice;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JScrollPane ValuesScrollPane;
    // End of variables declaration//GEN-END:variables
}
